title: Front-End Web Developer
author: Yuribenjamin
email: Abrahammoustafa@hotmail.co.uk
description: > # this means to ignore newlines until "baseurl:"
  Creates the environment for everything that users interact with: content, layout, interaction and user experience with scripts embedded in HTML. Tailoring user experience by bringing a developer concept to life with HTML, CSS, responsive, JavaScript, testing, APIs, React Guarantee production, modification, and maintenance of websites and web application user interfaces.

# social links
twitter_username: your-twitter-handle
github_username:  your-github-handle

show_excerpts: true # set to false to remove excerpts on the homepage

theme: minima
